version: "3.7"

services:
  postgresql:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ddproject
    ports:
      - "5432:5432"
    volumes:
      - ddproject-postgres-data:/var/lib/ddproject/postgresql/data
    restart: always
    networks:
      - java-2023

volumes:
  ddproject-postgres-data:
networks:
  java-2023:
